from .darcy import (
    physics_loss_pressure,
    physics_loss_saturation,
    grad_x,
    grad_y,
    divergence,
    mobility,
    rel_perm,
    brooks_corey_rel_perm,
    BrooksCoreyModel,
    TwoPhaseDarcyPhysics,
    grad_x_3d,
    grad_y_3d,
    grad_z_3d,
    divergence_3d,
    darcy_residual_3d,
    spectral_darcy_residual_3d,
    spectral_darcy_residual_2d,
)
from .reactive_transport import ReactiveTransportPhysics

__all__ = [
    "physics_loss_pressure",
    "physics_loss_saturation",
    "grad_x",
    "grad_y",
    "divergence",
    "mobility",
    "rel_perm",
    "brooks_corey_rel_perm",
    "BrooksCoreyModel",
    "TwoPhaseDarcyPhysics",
    "ReactiveTransportPhysics",
    "grad_x_3d",
    "grad_y_3d",
    "grad_z_3d",
    "divergence_3d",
    "darcy_residual_3d",
    "spectral_darcy_residual_3d",
    "spectral_darcy_residual_2d",
]
