#!/usr/bin/env python
"""
Generate multi-fidelity Tier 1 (coarse-grid) 3D Darcy data.

Multi-fidelity pretraining motivation:
  - Tier 0 (free): permeability fields generated by Gaussian random field
  - Tier 1 (cheap): COARSE-grid simulations — same physics, downsampled grid,
    looser solver tolerance, ~10-50x cheaper per sample than fine-grid
  - Tier 2 (expensive): fine-grid simulations for downstream fine-tuning

This script generates Tier 1 data using the same single-phase Darcy
formulation as generate_darcy_data_3d.py, but on a coarser grid. The
field at Tier 1's native resolution is *upsampled* to match the Tier 2
encoder's expected resolution, so the same PI-JEPA encoder can consume
either tier without retraining.

Output: torch .pt with `x_coarse_native` (raw coarse field), `x_upsampled`
(coarse field bilinearly upsampled to Tier 2 resolution), `y_upsampled`
(coarse-solved pressure upsampled to Tier 2 resolution).

The "upsampled" tensors are what the trainer consumes; the native tensors
are kept so we can report Tier 1's true compute cost honestly.
"""

import argparse
import math
import os
from typing import Tuple

import numpy as np
import torch
import torch.nn.functional as F
from scipy import sparse
from scipy.sparse.linalg import cg


# Re-use the GRF and 3D Poisson assembly from the Tier 2 generator.
import sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from generate_darcy_data_3d import (
    gaussian_random_field_3d,
    build_poisson_matrix_3d,
)


def solve_one_tier1_sample(
    resolution: int,
    length_scale: float,
    variance: float,
    rng: np.random.Generator,
    cg_rtol: float = 1e-3,
    cg_maxiter: int = 500,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return (K_coarse, p_coarse) on the coarse grid.

    Tier 1 uses a much looser CG tolerance and lower maxiter than Tier 2
    to simulate the "cheap solver" knob reservoir engineers use in
    practice.
    """
    N = resolution
    logK = gaussian_random_field_3d(N, length_scale, variance, rng)
    K = np.exp(logK)

    A = build_poisson_matrix_3d(K)

    coords = (np.arange(N) - (N - 1) / 2.0) / N
    zz, yy, xx = np.meshgrid(coords, coords, coords, indexing="ij")
    width = 0.1
    q = np.exp(-(xx ** 2 + yy ** 2 + zz ** 2) / (2 * width ** 2))
    q = q[1:-1, 1:-1, 1:-1].reshape(-1)

    p_int, info = cg(A, q, rtol=cg_rtol, maxiter=cg_maxiter)
    # Don't fail on non-convergence — this is Tier 1, "cheap and approximate".

    p = np.zeros((N, N, N), dtype=np.float32)
    p[1:-1, 1:-1, 1:-1] = p_int.reshape(N - 2, N - 2, N - 2)
    return K.astype(np.float32), p


def upsample_to_target(arr: np.ndarray, target_res: int, mode: str = "trilinear") -> np.ndarray:
    """Bilinear/trilinear upsample a single (R, R, R) array to (T, T, T)."""
    t = torch.from_numpy(arr).float()
    # F.interpolate wants (N, C, D, H, W); we have (D, H, W) so add 2 dims.
    t = t.unsqueeze(0).unsqueeze(0)
    out = F.interpolate(t, size=(target_res, target_res, target_res), mode=mode, align_corners=False)
    return out.squeeze(0).squeeze(0).numpy().astype(np.float32)


def main():
    ap = argparse.ArgumentParser(
        description="Generate Tier 1 (coarse-grid) 3D Darcy data for multi-fidelity pretraining"
    )
    ap.add_argument("--n-samples", type=int, default=128,
                    help="Tier 1 is meant to be CHEAP, so default n is larger than Tier 2")
    ap.add_argument("--coarse-resolution", type=int, default=16,
                    help="Native coarse grid (e.g., 16 = 16^3 voxels)")
    ap.add_argument("--target-resolution", type=int, default=32,
                    help="Resolution to upsample to (should match Tier 2 / encoder)")
    ap.add_argument("--length-scale", type=float, default=0.15)
    ap.add_argument("--variance", type=float, default=0.5)
    ap.add_argument("--cg-rtol", type=float, default=1e-3)
    ap.add_argument("--cg-maxiter", type=int, default=500)
    ap.add_argument("--seed", type=int, default=43)
    ap.add_argument("--out-dir", type=str, default="data/darcy_3d_tier1")
    ap.add_argument("--normalize", action="store_true", default=True)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    Ks_native, ps_native = [], []
    Ks_up, ps_up = [], []

    print(f"Generating {args.n_samples} Tier 1 samples at {args.coarse_resolution}^3 "
          f"-> upsampled to {args.target_resolution}^3 ...")

    for i in range(args.n_samples):
        K, p = solve_one_tier1_sample(
            args.coarse_resolution,
            args.length_scale,
            args.variance,
            rng,
            cg_rtol=args.cg_rtol,
            cg_maxiter=args.cg_maxiter,
        )
        Ks_native.append(K)
        ps_native.append(p)

        K_up = upsample_to_target(K, args.target_resolution, mode="trilinear")
        p_up = upsample_to_target(p, args.target_resolution, mode="trilinear")
        Ks_up.append(K_up)
        ps_up.append(p_up)

        if (i + 1) % max(1, args.n_samples // 10) == 0:
            print(f"  sample {i+1}/{args.n_samples}")

    K_native = np.stack(Ks_native, axis=0)[:, None, ...]  # (N, 1, r, r, r)
    p_native = np.stack(ps_native, axis=0)[:, None, ...]
    K_up = np.stack(Ks_up, axis=0)[:, None, ...]           # (N, 1, T, T, T)
    p_up = np.stack(ps_up, axis=0)[:, None, ...]

    blob = {
        "x_coarse_native": torch.from_numpy(K_native),
        "y_coarse_native": torch.from_numpy(p_native),
        "x_upsampled": torch.from_numpy(K_up),
        "y_upsampled": torch.from_numpy(p_up),
        "metadata": {
            "tier": 1,
            "coarse_resolution": args.coarse_resolution,
            "target_resolution": args.target_resolution,
            "n_samples": args.n_samples,
            "cg_rtol": args.cg_rtol,
            "cg_maxiter": args.cg_maxiter,
            "length_scale": args.length_scale,
            "variance": args.variance,
            "seed": args.seed,
        },
    }

    if args.normalize:
        # Normalize the UPSAMPLED tensors over the batch so they're directly
        # usable by the trainer. Keep the native tensors raw so cost reporting
        # stays interpretable.
        for key in ("x_upsampled", "y_upsampled"):
            t = blob[key]
            mean = t.mean()
            std = t.std() + 1e-8
            blob[key] = (t - mean) / std

    out_path = os.path.join(args.out_dir, "darcy3d_tier1.pt")
    torch.save(blob, out_path)
    print(f"Saved {out_path}")
    print(f"  x_upsampled shape: {tuple(blob['x_upsampled'].shape)}")
    print(f"  y_upsampled shape: {tuple(blob['y_upsampled'].shape)}")
    print(f"  x_coarse_native shape: {tuple(blob['x_coarse_native'].shape)}")
    print(f"  y_coarse_native shape: {tuple(blob['y_coarse_native'].shape)}")


if __name__ == "__main__":
    main()
